export const categories = [
  { id: "all", label: "Tüm araçlar", icon: "grid" },
  { id: "favorites", label: "Favorilerim", icon: "star" },
  { id: "organize", label: "Düzenle", icon: "layers" },
  { id: "convert", label: "Dönüştür", icon: "refresh" },
  { id: "optimize", label: "Optimize et", icon: "sliders" },
  { id: "security", label: "Güvenlik", icon: "shield" },
];
// Routes are the real, vendored BentoPDF tool pages; never advertise placeholder operations.
export const tools = [
  {
    id: "merge-pdf",
    name: "PDF birleştir",
    description: "Birden fazla PDF’i tek bir belgede toplayın.",
    category: "organize",
    icon: "merge",
    color: "rose",
    popular: true,
  },
  {
    id: "split-pdf",
    name: "PDF böl",
    description: "İhtiyacınız olan sayfaları ayrı dosyalara ayırın.",
    category: "organize",
    icon: "split",
    color: "peach",
    popular: true,
  },
  {
    id: "compress-pdf",
    name: "PDF sıkıştır",
    description: "Dosya boyutunu azaltın, paylaşmayı kolaylaştırın.",
    category: "optimize",
    icon: "compress",
    color: "sage",
    popular: true,
  },
  {
    id: "repair-pdf",
    name: "PDF onar",
    description: "Bozuk veya hasarlı PDF dosyalarındaki verileri kurtarmayı deneyin.",
    category: "optimize",
    icon: "refresh",
    color: "peach",
  },
  {
    id: "deskew-pdf",
    name: "Eğik PDF’yi düzelt",
    description: "Taranmış ve eğik sayfaları otomatik olarak hizalayın.",
    category: "optimize",
    icon: "scan",
    color: "blue",
  },
  {
    id: "edit-pdf",
    name: "PDF düzenle",
    description: "Metin, şekil ve notlarla belgenize dokunun.",
    category: "organize",
    icon: "edit",
    color: "blue",
    popular: true,
  },
  {
    id: "form-filler",
    name: "PDF form doldur",
    description: "Doldurulabilir PDF formlarını doğrudan tarayıcınızda tamamlayın.",
    category: "organize",
    icon: "edit",
    color: "sage",
  },
  {
    id: "header-footer",
    name: "Üst bilgi ve alt bilgi",
    description: "PDF sayfalarının üst ve alt bölümlerine metin ekleyin.",
    category: "organize",
    icon: "file",
    color: "sand",
  },
  {
    id: "table-of-contents",
    name: "İçindekiler oluştur",
    description: "PDF yer imlerinden bir içindekiler sayfası oluşturun.",
    category: "organize",
    icon: "layers",
    color: "lilac",
  },
  {
    id: "remove-blank-pages",
    name: "Boş sayfaları kaldır",
    description: "Belgedeki boş sayfaları otomatik olarak tespit edip kaldırın.",
    category: "organize",
    icon: "trash",
    color: "peach",
  },
  {
    id: "compare-pdfs",
    name: "PDF karşılaştır",
    description: "İki PDF belgesini yan yana açarak farklılıklarını inceleyin.",
    category: "organize",
    icon: "layers",
    color: "rose",
  },
  {
    id: "jpg-to-pdf",
    name: "Görselden PDF’e",
    description: "JPG görsellerinizi bir PDF belgesine dönüştürün.",
    category: "convert",
    icon: "image",
    color: "sand",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF’ten JPG’ye",
    description: "PDF sayfalarını yüksek kaliteli görsellere çevirin.",
    category: "convert",
    icon: "image-out",
    color: "lilac",
  },
  {
    id: "pdf-to-docx",
    name: "PDF’den Word’e",
    description: "PDF belgelerinizi düzenlenebilir Word dosyalarına dönüştürün.",
    category: "convert",
    icon: "file",
    color: "blue",
  },
  {
    id: "pdf-to-excel",
    name: "PDF’den Excel’e",
    description: "PDF tablolarını düzenlenebilir Excel çalışma kitabına dönüştürün.",
    category: "convert",
    icon: "grid",
    color: "sage",
  },
  {
    id: "pdf-to-text",
    name: "PDF’den metne",
    description: "PDF belgelerindeki metinleri TXT dosyası olarak kaydedin.",
    category: "convert",
    icon: "file-out",
    color: "blue",
  },
  {
    id: "extract-images",
    name: "Görselleri çıkar",
    description: "PDF dosyalarına gömülü görselleri toplu olarak dışa aktarın.",
    category: "convert",
    icon: "image-out",
    color: "lilac",
  },
  {
    id: "rotate-pdf",
    name: "Sayfaları döndür",
    description: "Sayfalarınızı doğru yöne kolayca çevirin.",
    category: "organize",
    icon: "rotate",
    color: "blue",
  },
  {
    id: "organize-pdf",
    name: "Sayfaları sırala",
    description: "Sürükleyip bırakın, belgenizin akışını düzenleyin.",
    category: "organize",
    icon: "layers",
    color: "rose",
  },
  {
    id: "delete-pages",
    name: "Sayfa sil",
    description: "Gereksiz sayfaları kaldırın, önemli olana yer açın.",
    category: "organize",
    icon: "trash",
    color: "peach",
  },
  {
    id: "extract-pages",
    name: "Sayfa çıkar",
    description: "Seçtiğiniz sayfalarla yeni bir PDF oluşturun.",
    category: "organize",
    icon: "file-out",
    color: "sage",
  },
  {
    id: "word-to-pdf",
    name: "Word’den PDF’e",
    description: "Word belgelerinizi PDF formatına dönüştürün.",
    category: "convert",
    icon: "file",
    color: "blue",
  },
  {
    id: "excel-to-pdf",
    name: "Excel’den PDF’e",
    description: "Çalışma tablolarınızı PDF olarak hazırlayın.",
    category: "convert",
    icon: "grid",
    color: "sage",
  },
  {
    id: "powerpoint-to-pdf",
    name: "PowerPoint’ten PDF’e",
    description: "Sunumlarınızı kolayca paylaşılabilir hale getirin.",
    category: "convert",
    icon: "presentation",
    color: "peach",
  },
  {
    id: "png-to-pdf",
    name: "PNG’den PDF’e",
    description: "PNG görsellerini bir PDF içinde bir araya getirin.",
    category: "convert",
    icon: "image",
    color: "sand",
  },
  {
    id: "pdf-to-png",
    name: "PDF’ten PNG’ye",
    description: "Belge sayfalarını PNG görselleri olarak kaydedin.",
    category: "convert",
    icon: "image-out",
    color: "lilac",
  },
  {
    id: "add-watermark",
    name: "Filigran ekle",
    description: "Belgelerinize metin veya görsel filigran ekleyin.",
    category: "security",
    icon: "stamp",
    color: "rose",
  },
  {
    id: "encrypt-pdf",
    name: "PDF şifrele",
    description: "Belgelerinizi bir parolayla koruma altına alın.",
    category: "security",
    icon: "lock",
    color: "sage",
  },
  {
    id: "decrypt-pdf",
    name: "Şifreyi kaldır",
    description: "Parolasını bildiğiniz PDF’in kilidini kaldırın.",
    category: "security",
    icon: "unlock",
    color: "sand",
  },
  {
    id: "sign-pdf",
    name: "İmza ekle",
    description: "İmzanızı çizin veya görsel olarak yerleştirin.",
    category: "security",
    icon: "pen",
    color: "lilac",
  },
  {
    id: "page-numbers",
    name: "Sayfa numarası ekle",
    description: "Uzun belgelerinizde gezinmeyi kolaylaştırın.",
    category: "organize",
    icon: "hash",
    color: "blue",
  },
  {
    id: "crop-pdf",
    name: "PDF kırp",
    description: "Kenar boşluklarını ayarlayın, içeriği öne çıkarın.",
    category: "organize",
    icon: "crop",
    color: "peach",
  },
  {
    id: "ocr-pdf",
    name: "Metin tanıma (OCR)",
    description: "Taranmış belgeleri aranabilir PDF’e dönüştürün.",
    category: "optimize",
    icon: "scan",
    color: "lilac",
  },
  {
    id: "flatten-pdf",
    name: "PDF düzleştir",
    description: "Formları ve açıklamaları sayfalara sabitleyin.",
    category: "optimize",
    icon: "layers",
    color: "sage",
  },
  {
    id: "edit-metadata",
    name: "Belge bilgilerini düzenle",
    description: "Başlık, yazar ve belge özelliklerini güncelleyin.",
    category: "optimize",
    icon: "info",
    color: "sand",
  },
];
